name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: make build

      - name: Run the unit tests
        run: make test

      - name: Lint the code
        run: make lint

      - name: Start the local gremlin as preparation for the integration test
        run: make infra.up

      - name: Run the integration tests
        run: make test.integration

      - name: Stop the local gremlin
        run: make infra.down
